version: "2"
services:
  redmine:
    image: redmine
    environment:
      VIRTUAL_HOST: redmine.example.com
      REDMINE_DB_PASSWORD: root
    external_links:
      - mysql
    restart: always
    logging:
      options:
        max-size: 5m
        max-file: "10"

networks:
  default:
    external:
      name: shared
